import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkThemeProvider } from "@/components/clerk-theme-provider"
import { SimpleAuthHandler } from "@/components/simple-auth-handler"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authEnabled = Boolean(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          {authEnabled ? (
            <ClerkThemeProvider>
              <SimpleAuthHandler />
              <div className="min-h-screen">{children}</div>
              <Toaster expand={false} closeButton position="bottom-right" />
            </ClerkThemeProvider>
          ) : (
            <>
              <div className="min-h-screen">{children}</div>
              <Toaster expand={false} closeButton position="bottom-right" />
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
